export const BLOCKS_GET_LATEST_START = 'BLOCKS_GET_LATEST_START';
export const BLOCKS_GET_LATEST_SUCCESS = 'BLOCKS_GET_LATEST_SUCCESS';
export const BLOCKS_GET_LATEST_FAILURE = 'BLOCKS_GET_LATEST_FAILURE';
