export const BLOCKS_GET_LATEST_START = 'BLOCKS_GET_LATEST_START';
export const BLOCKS_GET_LATEST_SUCCESS = 'BLOCKS_GET_LATEST_SUCCESS';
export const BLOCKS_GET_LATEST_FAILURE = 'BLOCKS_GET_LATEST_FAILURE';

export const VALIDATORS_GET_START = 'VALIDATORS_GET_START';
export const VALIDATORS_GET_SUCCESS = 'VALIDATORS_GET_SUCCESS';
export const VALIDATORS_GET_FAILURE = 'VALIDATORS_GET_FAILURE';

export const VALIDATORS_GET_LATEST_START = 'VALIDATORS_GET_LATEST_START';
export const VALIDATORS_GET_LATEST_SUCCESS = 'VALIDATORS_GET_LATEST_SUCCESS';
export const VALIDATORS_GET_LATEST_FAILURE = 'VALIDATORS_GET_LATEST_FAILURE';
