export const mockResponseDepositors = {
    result: [
        {
            id: '21:lumvaloper1ss7vkqzfal7h4m8ug8lh8peqqyt7vq3sjr9zvg',
            proposal_id: 21,
            depositor_address: 'lumvaloper1ss7vkqzfal7h4m8ug8lh8peqqyt7vq3sjr9zvg',
            amount: {
                denom: '0000636363636366',
                amount: '0000136363636311',
            },
        },
    ],
    metadata: {
        page: 0,
        limit: 5,
        items_count: 1,
        items_total: 1,
        pages_total: 1,
        has_previous_page: false,
        has_next_page: false,
    },
    code: 200,
    message: '',
};

export const mockResponseVotersPage0 = {
    result: [
        {
            id: '21:lum14a3kmsuu75njmfe3xj9wt5sld5gw88vdfrn9kv',
            proposal_id: 21,
            voter_address: 'lum14a3kmsuu75njmfe3xj9wt5sld5gw88vdfrn9kv',
            voter_operator_address: 'lumvaloper14a3kmsuu75njmfe3xj9wt5sld5gw88vdk56kdg',
            vote_option: 1,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1aqzs28dufw3p9jrvtwtpke4c4lutnxfsclw08z',
            proposal_id: 21,
            voter_address: 'lum1aqzs28dufw3p9jrvtwtpke4c4lutnxfsclw08z',
            voter_operator_address: 'lumvaloper1aqzs28dufw3p9jrvtwtpke4c4lutnxfs8g8uux',
            vote_option: 3,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1e9hr3fnf749sv40yge30dcz2jxrrwh9lw8yhrc',
            proposal_id: 21,
            voter_address: 'lum1e9hr3fnf749sv40yge30dcz2jxrrwh9lw8yhrc',
            voter_operator_address: 'lumvaloper1e9hr3fnf749sv40yge30dcz2jxrrwh9l3sdycu',
            vote_option: 4,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1mjxsv6j9e2srh36ncsuj5yhlxa0vu97a6rjl47',
            proposal_id: 21,
            voter_address: 'lum1mjxsv6j9e2srh36ncsuj5yhlxa0vu97a6rjl47',
            voter_operator_address: 'lumvaloper1mjxsv6j9e2srh36ncsuj5yhlxa0vu97a95mvw6',
            vote_option: 0,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1ny8y5e9js03xnz9wv4s3n4u05yz8x50fuvm87c',
            proposal_id: 21,
            voter_address: 'lum1ny8y5e9js03xnz9wv4s3n4u05yz8x50fuvm87c',
            voter_operator_address: 'lumvaloper1ny8y5e9js03xnz9wv4s3n4u05yz8x50frmj59u',
            vote_option: 1,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
    ],
    metadata: {
        page: 0,
        limit: 5,
        items_count: 5,
        items_total: 10,
        pages_total: 2,
        has_previous_page: false,
        has_next_page: true,
    },
    code: 200,
    message: '',
};

export const mockResponseVotersPage1 = {
    result: [
        {
            id: '21:lum1p02gahyrqn68weajhy7gaxyx4gzlvfn6gy2nvr',
            proposal_id: 21,
            voter_address: 'lum1p02gahyrqn68weajhy7gaxyx4gzlvfn6gy2nvr',
            voter_operator_address: 'lumvaloper1p02gahyrqn68weajhy7gaxyx4gzlvfn6hnrqh8',
            vote_option: 2,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1sfc34ujkys84eeqmegm7lle955y3edyt47rpc5',
            proposal_id: 21,
            voter_address: 'lum1sfc34ujkys84eeqmegm7lle955y3edyt47rpc5',
            voter_operator_address: 'lumvaloper1sfc34ujkys84eeqmegm7lle955y3edyt2f2jrs',
            vote_option: 2,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1ss7vkqzfal7h4m8ug8lh8peqqyt7vq3sd5v3hv',
            proposal_id: 21,
            voter_address: 'lum1ss7vkqzfal7h4m8ug8lh8peqqyt7vq3sd5v3hv',
            voter_operator_address: 'lumvaloper1ss7vkqzfal7h4m8ug8lh8peqqyt7vq3sjr9zvg',
            vote_option: 3,
            vote_weight: 'yes',
            voted_by_operator_address: true,
        },
        {
            id: '21:lum1xjvhpmflhue38mc8j75gqj2h0fds9guxaga7p5',
            proposal_id: 21,
            voter_address: 'lum1xjvhpmflhue38mc8j75gqj2h0fds9guxaga7p5',
            voter_operator_address: 'lumvaloper1xjvhpmflhue38mc8j75gqj2h0fds9guxzl5d6s',
            vote_option: 2,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
        {
            id: '21:lum1yhaswwgg5tz7veknxwaj8vc8rfa9s0nahkjq30',
            proposal_id: 21,
            voter_address: 'lum1yhaswwgg5tz7veknxwaj8vc8rfa9s0nahkjq30',
            voter_operator_address: 'lumvaloper1yhaswwgg5tz7veknxwaj8vc8rfa9s0nagpmn2t',
            vote_option: 3,
            vote_weight: 'yes',
            voted_by_operator_address: false,
        },
    ],
    metadata: {
        page: 1,
        limit: 5,
        items_count: 5,
        items_total: 10,
        pages_total: 2,
        has_previous_page: true,
        has_next_page: false,
    },
    code: 200,
    message: '',
};
