export const BLOCKS_GET_LATEST_START = 'BLOCKS_GET_LATEST_START';
export const BLOCKS_GET_LATEST_SUCCESS = 'BLOCKS_GET_LATEST_SUCCESS';
export const BLOCKS_GET_LATEST_FAILURE = 'BLOCKS_GET_LATEST_FAILURE';

export const BLOCKS_GET_START = 'BLOCKS_GET_START';
export const BLOCKS_GET_SUCCESS = 'BLOCKS_GET_SUCCESS';
export const BLOCKS_GET_FAILURE = 'BLOCKS_GET_FAILURE';

export const BLOCK_GET_START = 'BLOCK_GET_START';
export const BLOCK_GET_SUCCESS = 'BLOCK_GET_SUCCESS';
export const BLOCK_GET_FAILURE = 'BLOCK_GET_FAILURE';

export const VALIDATORS_GET_START = 'VALIDATORS_GET_START';
export const VALIDATORS_GET_SUCCESS = 'VALIDATORS_GET_SUCCESS';
export const VALIDATORS_GET_FAILURE = 'VALIDATORS_GET_FAILURE';

export const VALIDATORS_GET_LATEST_START = 'VALIDATORS_GET_LATEST_START';
export const VALIDATORS_GET_LATEST_SUCCESS = 'VALIDATORS_GET_LATEST_SUCCESS';
export const VALIDATORS_GET_LATEST_FAILURE = 'VALIDATORS_GET_LATEST_FAILURE';

export const ACCOUNT_GET_START = 'ACCOUNT_GET_START';
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS';
export const ACCOUNT_GET_FAILURE = 'ACCOUNT_GET_FAILURE';
