version: '3.8'
services:
  lm-bridge-redis:
    image: redis:5
    command: [ sh, -c, "rm -f /data/dump.rdb && redis-server" ]  # disable persistence
    ports:
      - "6379:6379"
  lm-bridge-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: emulator
  lm-node:
    logging:
      driver: none
    image: rg.fr-par.scw.cloud/lum-network/chain:latest
    command:
      - /bin/sh
      - -c
      - |
        lumd unsafe-reset-all
        lumd keys add genesis_key
        lumd init genesis_key --chain-id=lum-network-devnet
        lumd add-genesis-account `lumd keys show genesis_key -a` 1000000000000000ulum
        lumd gentx genesis_key 1000000ulum --chain-id=lum-network-devnet
        lumd collect-gentxs
        sed -i 's/"stake"/"ulum"/g' /chain/.lumd/config/genesis.json
        sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "0.001ulum"/g' /chain/.lumd/config/app.toml
        sed -i 's/timeout_propose = "3s"/timeout_propose = "1s"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_propose_delta = "500ms"/timeout_propose_delta = "200ms"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_prevote = "1s"/timeout_prevote = "300ms"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_prevote_delta = "500ms"/timeout_prevote_delta = "200ms"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_precommit = "1s"/timeout_precommit = "300ms"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_precommit_delta = "500ms"/timeout_precommit_delta = "200ms"/g' /chain/.lumd/config/config.toml
        sed -i 's/timeout_commit = "5s"/timeout_commit = "2s"/g' /chain/.lumd/config/config.toml
        lumd start --rpc.laddr tcp://0.0.0.0:26657
    ports:
      - "26657:26657"
