name: Lint, format and test the bridge on pull request events
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    build:
        name: Build, lint, format the code and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-python@v1
              with:
                  python-version: '3.x'
                  architecture: 'x64'

            - uses: actions/setup-node@v1
              with:
                  node-version: '18.19.0'

            - name: Install the project dependencies
              run: yarn install

            - name: Format the code
              run: yarn format

            - name: Lint the code
              run: yarn lint

            - name: Start docker containers
              working-directory: tools
              run: docker-compose up -d

            - name: Install dependencies
              run: yarn install

            - name: Start server and start e2e tests
              run: yarn start:api:dev & yarn test:e2e
              timeout-minutes: 15
              env:
                  LUM_NETWORK_ENDPOINT: https://node0.mainnet.lum.network/rpc
                  DATABASE_URL: postgresql://postgres:emulator@127.0.0.1:5432/postgres
                  REDIS_URL: redis://127.0.0.1:6379
                  GOVERNANCE_SYNC_ENABLED: true
                  METRIC_SYNC_ENABLED: true
                  VALIDATOR_SYNC_ENABLED: true
                  BULLBOARD_PASSWORD: admin
                  DFRACT_SYNC_ENABLED: true
                  MILLIONS_SYNC_ENABLED: true
                  REDIS_PREFIX: lm-bridge
                  INGEST_ENABLED: true
                  INGEST_BACKWARD_ENABLED: false
                  FAUCET_MNEMONIC: 'my mnemonic phrase'
                  PORT: 3000
                  ENV: development
                  STARTING_HEIGHT: 9165230

            - name: Stop docker containers
              working-directory: tools
              run: docker-compose down
